droP DATABASE TRAJEDIA;
CREATE DATABASE TRAJEDIA;

USE TRAJEDIA;

CREATE TABLE CATEGORIA(
IDCATEGORIA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(45) NOT NULL
);

CREATE TABLE ROUPA(
IDROUPA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(100),
VLR DOUBLE NOT NULL,
IDCATEGORIA INT NOT NULL,
ATIVO INT DEFAULT 1,
FOREIGN KEY(IDCATEGORIA) REFERENCES CATEGORIA(IDCATEGORIA)
);

CREATE TABLE ENDERECO(
IDENDERECO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NUMERO VARCHAR(45) NOT NULL,
RUA VARCHAR(45) NOT NULL,
BAIRRO VARCHAR(45) NOT NULL,
CIDADE VARCHAR(45) NOT NULL,
ESTADO VARCHAR(45) NOT NULL,
UF VARCHAR(45) NOT NULL,
PAIS VARCHAR(45) NOT NULL,
ATIVO INT DEFAULT 1
);

CREATE TABLE FUNCIONARIO(
IDFUNCIONARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
USUARIO VARCHAR(100),
SENHA VARCHAR(100),
ATIVO INT DEFAULT 1
);

CREATE TABLE FORNECEDOR(
IDFORNECEDOR INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
RAZAOSOCIAL VARCHAR(45) NOT NULL,
IDENDERECO INT NOT NULL,
TELEFONE VARCHAR(16) NOT NULL,
ATIVO INT DEFAULT 1,
FOREIGN KEY (IDENDERECO) REFERENCES ENDERECO (IDENDERECO)
);

CREATE TABLE TRAJE(
IDTRAJE INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(45) NOT NULL,
DESCONTO INT NOT NULL,
IDFORNECEDOR INT,
ATIVO INT DEFAULT 1,	
PRIMARY KEY(IDTRAJE),
FOREIGN KEY (IDFORNECEDOR) REFERENCES FORNECEDOR(IDFORNECEDOR)
);

CREATE TABLE ROUPAVENDA(
IDROUPAVENDA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
DESCONTO INT NOT NULL
);

CREATE TABLE ROUPADOTRAJE(
IDTRAJE INT NOT NULL,
IDROUPA INT NOT NULL,
PRIMARY KEY(IDTRAJE,IDROUPA),
FOREIGN KEY(IDTRAJE) REFERENCES TRAJE(IDTRAJE),
FOREIGN KEY(IDROUPA) REFERENCES ROUPA(IDROUPA),
FOREIGN KEY(IDROUPA) REFERENCES ROUPAVENDA(IDROUPAVENDA)
);

CREATE TABLE CLIENTE(
IDCLIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(45) NOT NULL,
CPF VARCHAR(11) NOT NULL,
TELEFONE VARCHAR(16) NOT NULL,
IDENDERECO INT NOT NULL,
ATIVO INT DEFAULT 1,
FOREIGN KEY (IDENDERECO) REFERENCES ENDERECO (IDENDERECO)
);

CREATE TABLE AGENDA(
IDAGENDA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
DTAGENDAMENTO DATETIME NOT NULL,
IDCLIENTE INT NOT NULL,
IDFUNCIONARIO INT NOT NULL,
FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE),
FOREIGN KEY(IDFUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO)
);

CREATE TABLE ESTOQUE(
IDESTOQUE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
QUANTIDADE INT NOT NULL,
IDROUPA INT NOT NULL,
FOREIGN KEY(IDROUPA) REFERENCES ROUPA(IDROUPA)
);

CREATE TABLE LOCACAO(
IDLOCACAO INT NOT NULL AUTO_INCREMENT,
DATALOCACAO DATETIME NOT NULL,
DATAEVENTO DATETIME NOT NULL,
VLRTOTAL DOUBLE NOT NULL,
DTDEVOLUCAO DATETIME NOT NULL,
IDFUNCIONARIO INT NOT NULL,
TIPODELOCACAO INT NOT NULL,
PRIMARY KEY (IDLOCACAO,TIPODELOCACAO),
FOREIGN KEY (IDFUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO)
);

CREATE TABLE TELA(
IDTELA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
INSTANCIA VARCHAR(100) NOT NULL,
NUMERODATELA INT
);

CREATE TABLE PERMISSAO(
IDPERMISSAO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
IDTELA INT NOT NULL,
VISUALIZAR INT NOT NULL,
EDITAR INT NOT NULL, 
CADASTRAR INT NOT NULL,
DELETAR INT NOT NULL,
IDFUNCIONARIO INT NOT NULL,
FOREIGN KEY(IDTELA) REFERENCES TELA(IDTELA),
FOREIGN KEY(IDFUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO)
);

CREATE TABLE TRAJEVENDA(
IDLOCACAO INT NOT NULL,
IDCLIENTE INT NOT NULL, 
IDTRAJE INT NOT NULL,
PRIMARY KEY(IDLOCACAO,IDCLIENTE),
FOREIGN KEY (IDLOCACAO) REFERENCES LOCACAO(IDLOCACAO),
FOREIGN KEY (IDTRAJE)  REFERENCES TRAJE (IDTRAJE),
FOREIGN KEY (IDTRAJE)  REFERENCES ROUPAVENDA (IDROUPAVENDA),
FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);

insert into categoria(NOME) values("Camisa");
insert into categoria(NOME) values("Calça");
insert into categoria(NOME) values("Tênis");
insert into categoria(NOME) values("Salto");
insert into categoria(NOME) values("Vestido");
insert into funcionario(USUARIO,SENHA) values("ADMIN","ADMIN");
UPDATE FUNCIONARIO SET ativo = 0 WHERE IDFUNCIONARIO = 1;


SELECT * FROM ROUPA ORDER BY IDROUPA DESC;

SELECT * FROM CLIENTE;


SELECT * FROM ENDERECO;


select * from cliente;
SELECT * FROM ENDERECO WHERE ATIVO = 0 ORDER BY IDENDERECO ASC;
SELECT * FROM ENDERECO;

SELECT 
*
FROM
CLIENTE
WHERE 
ATIVO = 1
ORDER BY IDCLIENTE;

SELECT * FROM FUNCIONARIO;

select idestoque, quantidade, idroupa from estoque order by idestoque desc;

SELECT
    IDROUPA  
    , SUM(QUANTIDADE)
FROM 
	ESTOQUE 
GROUP BY 
    IDROUPA
ORDER BY
	IDROUPA ASC;

SELECT * FROM TRAJE;